### ISSUE TITLE
Different topics shown in rqt_graph as same topic when using namespaces and underscores

### ISSUE THREAD

**Issue by Ellon** [ros-visualization/rqt_graph#11]
When I use the following launch file:

```xml
<launch>
  <!-- launch talker and listener, remmaping 'chatter' to 'myns_chatter' -->
  <node pkg="roscpp_tutorials" type="talker" name="talker1">
    <remap from="chatter" to="myns_chatter"/>
  </node>
  <node pkg="roscpp_tutorials" type="listener" name="listener1">
    <remap from="chatter" to="myns_chatter"/>
  </node>
  <!-- launch talker and listener, without remapping, in a namespace 'myns'. -->
  <node pkg="roscpp_tutorials" type="talker" name="talker2" ns="myns" />
  <node pkg="roscpp_tutorials" type="listener" name="listener2" ns="myns" />
</launch>
```
I get the following graph in rqt_graph: 
<img width="380" alt="rqt_graph_slash_problem" src="https://cloud.githubusercontent.com/assets/2206351/26727255/665f9ef6-47a6-11e7-8b80-ad0fe92ac10f.png">
When in fact `rostopic list` shows that there are two distinct chatter topics, one global prefixed with `myns_` and other with `myns/` because of the namespace:
```
$ rostopic list 
/myns/chatter
/myns_chatter
/rosout
/rosout_agg
/statistics
```

AFAIK they are different topics in ROS, so they should be represented by different topics in rqt_graph, no? Is that any reason to not distinguish `/` from `_` in rqt_graph, or would it be a bug?

I'm using Indigo in Ubuntu 14.04.4 LTS, with packages installed from Ubuntu repositories.

This question was originally posted in [ROS Answers](http://answers.ros.org/question/251817/different-topics-shown-in-rqt_graph-as-same-topic-when-using-namespaces-and-underscores/).

**Comment by dirk-thomas** [comment]
Please try the patch proposed in ros-visualization/qt_gui_core#95 and comment if it fixes the problem for you.

**Comment by Ellon** [comment]
I'll try later this week. Thanks!

**Comment by dirk-thomas** [comment]
I will go ahead and merge the patch from ros-visualization/qt_gui_core#95.

**Comment by Ellon** [comment]
Sorry for the late reply. I confirm ros-visualization/qt_gui_core#95 fixed the bug.

![rqt_graph_fixed](https://user-images.githubusercontent.com/2206351/28320160-22f26a24-6bd0-11e7-8999-129c0baf47ed.png)


Thanks for fixing this!
