### ISSUE TITLE
Adding Services in the Graph

### ISSUE THREAD

**Issue by nathangeorge1** [ros-visualization/rqt_graph#14]
Hello,

For rqt_graph, can an enhancement be made so that services are visualized, in addition to topics?

Thanks,
Nathan

**Comment by dirk-thomas** [comment]
While this is a great feature idea it is not something the maintainers will have time to implement. Please consider contributing a pull request for this enhancement.

**Comment by nathangeorge1** [comment]
Sounds good. Could you give me some guidance in how to technically do that, in this package?

**Comment by nathangeorge1** [comment]
Thanks. Sometime in the next month, I'll let you know if I think I can create a PR, cause this looks complicated.

**Comment by dirk-thomas** [comment]
Actually I don't even think the necessary information is available through any API. Therefore I don't think this feature is implementable.

Therefore I will close this ticket for now. Please feel free to comment on it anyway.

**Comment by nathangeorge1** [comment]
O that's too bad; let me know if something changes.
