### ISSUE TITLE
ROS2 : No executable found

### ISSUE THREAD

**Issue by EAR-Development** [ros-visualization/rqt_graph#26]
When I build rqt-graph in crystal, I get the following Error when running it.
`
$ ros2 run rqt_graph rqt_graph =>
No executable found
`

Adding a setup.cfg with
```
[develop]
script-dir=$base/lib/rqt_graph
[install]
install-scripts=$base/lib/rqt_graph
```

solves the problem, but i'm not sure, if this is the correct approach.
Is there a way to build it without this config file?

**Comment by dirk-thomas** [comment]
Currently the `rqt_graph` script is being installed into `bin` so you can only call it by name - not using `ros2 run`.

The location could be change to install the file in `lib/rqt_graph` but then again the global invocation wouldn't work. But this would match the ROS 1 behavior so changing it would make sense.

Can you please create a pull request with the proposed change.

**Comment by dirk-thomas** [comment]
Closing due to no response.
