### ISSUE TITLE
[ROS2] Nodes only graph missing edges

### ISSUE THREAD

**Issue by maryaB-osr** [ros-visualization/rqt_graph#32]
There are no arrows between the nodes when the graph is set to "Nodes only".

It seems like there should be, since [this tutorial for ROS 1](http://wiki.ros.org/ROS/Tutorials/UnderstandingTopics) shows arrows connecting the nodes in screenshots of rqt_graph where you can see the graph is set to "Nodes only"

(Fixing this bug will help make the tutorials less confusing)

**Comment by wjwwood** [comment]
Just to demonstrate what @maryaB-osr is talking about, here's two screenshots of the two different modes:

![Screen Shot 2019-10-04 at 1 58 50 PM](https://user-images.githubusercontent.com/100427/66239602-2c651c80-e6af-11e9-99f2-6b411d206134.png)
![Screen Shot 2019-10-04 at 1 58 59 PM](https://user-images.githubusercontent.com/100427/66239605-2ff8a380-e6af-11e9-9a1c-a18d6346b3b9.png)

The first screenshot should have an arrow between the nodes for the `/turtle1/cmd_vel` topic.

**Comment by hidmic** [comment]
This was addressed in https://github.com/ros-visualization/rqt_graph/pull/35. Closing.
