### ISSUE TITLE
ROS1 Melodic on Windows 10 Icons not displaying

### ISSUE THREAD

**Issue by arek20** [ros-visualization/rqt_graph#38]
Icons are not displaying in rqt_graph for Melodic on Windows 10
Please see: https://github.com/ros-visualization/rqt_plot/issues/42#issue-522507963

**Comment by dirk-thomas** [comment]
I will close this as a duplicate of a more generic ticket in `qt_gui_core` where the change would need to happen: ros-visualization/qt_gui_core#238.
