### ISSUE TITLE
Option to group/ignore dynamic_reconfigure topics

### ISSUE THREAD

**Issue by dirk-thomas** [ros-visualization/rqt_graph#4]
_From @DLu on August 13, 2015 19:49_

All my graphs are cluttered with ~parameter_descriptions and ~parameter_updates. 

_Copied from original issue: ros-visualization/rqt_common_plugins#334_

**Comment by dirk-thomas** [comment]
_From @dkargin on December 24, 2015 10:33_

You can add filter, some sort of: -(._parameter_updates),-(._parameter_descriptions)

**Comment by MasterEric** [comment]
This issue is resolved in ros_visualization/rqt_graph#9
