### ISSUE TITLE
"AttributeError: 'EdgeItem' object has no attribute '_path'" When Running qt_graph

### ISSUE THREAD

**Issue by songyuc** [ros-visualization/rqt_graph#41]
Hi guys,
I am learning about ROS2 on Windows 10 today, and when I run qt_graph, an error appeared as:

> RosPluginProvider._parse_plugin_xml() plugin file "E:\dev\ros2-eloquent\ros2-windows\share\qt_gui_cpp/plugin.xml" in package "qt_gui_cpp" not found
> RosPluginProvider._parse_plugin_xml() plugin file "E:\dev\ros2-eloquent\ros2-windows\share\rqt_gui_cpp/plugin.xml" in package "rqt_gui_cpp" not found
> RosPluginProvider._parse_plugin_xml() plugin file "E:\dev\ros2-eloquent\ros2-windows\share\qt_gui_cpp/plugin.xml" in package "qt_gui_cpp" not found
> RosPluginProvider._parse_plugin_xml() plugin file "E:\dev\ros2-eloquent\ros2-windows\share\rqt_gui_cpp/plugin.xml" in package "rqt_gui_cpp" not found
> PluginHandlerDirect._restore_settings() plugin "rqt_graph/RosGraph#0" raised an exception:
> Traceback (most recent call last):
>   File "E:\dev\ros2-eloquent\ros2-windows\Lib\site-packages\qt_gui\plugin_handler_direct.py", line 121, in _restore_settings
>     self._plugin.restore_settings(plugin_settings_plugin, instance_settings_plugin)
>   File "E:\dev\ros2-eloquent\ros2-windows\Lib\site-packages\rqt_graph\ros_graph.py", line 265, in restore_settings
>     self._refresh_rosgraph()
>   File "E:\dev\ros2-eloquent\ros2-windows\Lib\site-packages\rqt_graph\ros_graph.py", line 293, in _refresh_rosgraph
>     self._update_graph_view(self._generate_dotcode())
>   File "E:\dev\ros2-eloquent\ros2-windows\Lib\site-packages\rqt_graph\ros_graph.py", line 334, in _update_graph_view
>     self._redraw_graph_view()
>   File "E:\dev\ros2-eloquent\ros2-windows\Lib\site-packages\rqt_graph\ros_graph.py", line 366, in _redraw_graph_view
>     scene=self._scene)
>   File "E:\dev\ros2-eloquent\ros2-windows\Lib\site-packages\qt_dotgraph\dot_to_qt.py", line 263, in dotcode_to_qt_items
>     edges = self.parse_edges(graph, nodes, highlight_level, same_label_siblings, scene=scene)
>   File "E:\dev\ros2-eloquent\ros2-windows\Lib\site-packages\qt_dotgraph\dot_to_qt.py", line 317, in parse_edges
>     scene=scene)
>   File "E:\dev\ros2-eloquent\ros2-windows\Lib\site-packages\qt_dotgraph\dot_to_qt.py", line 221, in addEdgeItem
>     style=style)
>   File "E:\dev\ros2-eloquent\ros2-windows\Lib\site-packages\qt_dotgraph\edge_item.py", line 112, in __init__
>     point2 = QPointF(float(parts[0]), -float(parts[1]))
> ValueError: could not convert string to float: '\\\r\n46.336'
> 
> Traceback (most recent call last):
>   File "E:\dev\ros2-eloquent\ros2-windows\Lib\site-packages\qt_dotgraph\node_item.py", line 133, in hoverEnterEvent
>     incoming_edge.set_node_color(self._COLOR_BLUE)
>   File "E:\dev\ros2-eloquent\ros2-windows\Lib\site-packages\qt_dotgraph\edge_item.py", line 172, in set_node_color
>     self._path.setPen(self._edge_pen)
> AttributeError: 'EdgeItem' object has no attribute '_path'

And I want to know how to fix this, so as to go on my learning.
Thanks in advance!

**Comment by dirk-thomas** [comment]
On a simple graph I can't reproduce the problem. Can you please provide reproducible steps with which running nodes you experience the above errors.

**Comment by dirk-thomas** [comment]
Closing due to no response.
