### ISSUE TITLE
Noetic removal of scripts argument got rid of global executable

### ISSUE THREAD

**Issue by sloretz** [ros-visualization/rqt_graph#44]
It looks like I made a mistake in https://github.com/ros-visualization/rqt_graph/pull/43 by removing the `scripts` argument from the `setup.py`. I mistakenly thought it was installing to the package bin, [but it actually installs to the global bin path](https://github.com/ros/catkin/blob/e1dff19803edbd3866c42bf65206b0136130469e/cmake/catkin_python_setup.cmake#L141). Meaning before #43 it would have been possible to either run `rosrun rqt_graph rqt_graph` or just plain  `rqt_graph`, but after #43 only the first one works.

PRs incoming

**Comment by ros-discourse** [comment]
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-noetic-call-for-testing/14203/1

**Comment by dirk-thomas** [comment]
All four PRs have been merged and released into Noetic.
