### ISSUE TITLE
Topic name on arrows not highlighted/colored anymore

### ISSUE THREAD

**Issue by mikaelarguedas** [ros-visualization/rqt_graph#7]
I didn't track down when the arrow coloration disappeared but I noticed that:
On [the tutorial](http://wiki.ros.org/ROS/Tutorials/UnderstandingTopics#Using_rqt_graph) screenshot:
![Image from tutorials](http://wiki.ros.org/ROS/Tutorials/UnderstandingTopics?action=AttachFile&do=get&target=rqt_graph_turtle_key2.png)

Current state as of 2017-05-18 11-53-19:
![screenshot from 2017-05-18 11-53-19](https://cloud.githubusercontent.com/assets/6644208/26218688/c7425a48-3bc0-11e7-9750-d0511a5f2762.png)

**Comment by dirk-thomas** [comment]
Addressed by ros-visualization/qt_gui_core#85.
