### ISSUE TITLE
error when saving to dot format 

### ISSUE THREAD

**Issue by RoeschFlo** [ros-visualization/rqt_graph#85]
Hello together, 
when I try to save a rqt_graph to a dot file, i get a empty dot file and the following error occurs:
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_graph/ros_graph.py", line 414, in _save_dot
    handle.write(self._current_dotcode)
TypeError: write(self, Union[QByteArray, bytes, bytearray]): argument 1 has unexpected type 'str'

Edit: i found out i have 2 different python versions 2.7 and 3.8  i will check if thats my problem 
Edit: cant solve the problem
the problem is not system dependent, i have thins problem on my working pc and on a new virtual machine

**Comment by mjs973** [comment]
This is a bug in rqt_graph. It was created when noetic switched to using python3. The problem is that the code is not consistent about the type of the internal variable self._current_dotcode.

Please provide **detailed** instructions on how to trigger this bug, as I don't use the rqt_graph tools.

**Comment by mjs973** [comment]
This problem was previously reported as #67 and fixed for ros2 (although looking at the patch, it doesn't seem to me like it correctly fixes the underlying issue.)

**Comment by RoeschFlo** [comment]
I trigger this bug, when i want to save a bunch of running ros nodes as a dot file. Exept sending you a crash file, i have no other or better instructions on how i trigger the bug. As i said, it happens every time when saving to the dot format. Do you wish other instructions on how to trigger this bug?
[_opt_ros_noetic_lib_rqt_gui_rqt_gui.1001.TXT](https://github.com/ros-visualization/rqt_graph/files/11309118/_opt_ros_noetic_lib_rqt_gui_rqt_gui.1001.TXT)

Thank you, with this help it works: https://github.com/ros-visualization/rqt_graph/issues/67

**Comment by mjs973** [comment]
You have not told us which rqt_graph app you are using. What steps do you take to save a dot file? What do you click? What do you type?

**Comment by RoeschFlo** [comment]
![Screenshot from 2023-04-25 11-35-14](https://user-images.githubusercontent.com/127499468/234237693-42b35720-b21e-4225-8484-c386c1f01adf.png)

it happens in every rqt app that has the function to save the node graph to a dot file. in the picture you can see where i click.

The following part is the package xml:

<package format="3">
  <name>rqt_graph</name>
  <version>0.4.14</version>
  <description>rqt_graph provides a GUI plugin for visualizing the ROS
      computation graph.<br />
      Its components are made generic so that other packages
      where you want to achieve graph representation can depend upon this pkg
      (use <a href = "http://www.ros.org/wiki/rqt_dep">rqt_dep</a> to find out
      the pkgs that depend. rqt_dep itself depends on rqt_graph too).
  </description>
  <maintainer email="dthomas@osrfoundation.org">Dirk Thomas</maintainer>
  <maintainer email="ablasdel@gmail.com">Aaron Blasdel</maintainer>

  <license>BSD</license>

  <url type="website">http://wiki.ros.org/rqt_graph</url>
  <url type="repository">https://github.com/ros-visualization/rqt_graph</url>
  <url type="bugtracker">https://github.com/ros-visualization/rqt_graph/issues</url>

  <author>Dirk Thomas</author>

  <buildtool_depend>catkin</buildtool_depend>

  <exec_depend version_gte="0.2.19">python_qt_binding</exec_depend>
  <exec_depend condition="$ROS_PYTHON_VERSION == 2">python-rospkg</exec_depend>
  <exec_depend condition="$ROS_PYTHON_VERSION == 3">python3-rospkg</exec_depend>
  <exec_depend>qt_dotgraph</exec_depend>
  <exec_depend>rosgraph</exec_depend>
  <exec_depend>rosgraph_msgs</exec_depend>
  <exec_depend>roslib</exec_depend>
  <exec_depend>rosnode</exec_depend>
  <exec_depend>rospy</exec_depend>
  <exec_depend>rosservice</exec_depend>
  <exec_depend>rostopic</exec_depend>
  <exec_depend>rqt_gui</exec_depend>
  <exec_depend>rqt_gui_py</exec_depend>

  <export>
    <architecture_independent/>
    <rqt_gui plugin="${prefix}/plugin.xml"/>
  </export>
</package>

**Comment by alexvaut** [comment]
In file "/opt/ros/noetic/lib/python3/dist-packages/rqt_graph/ros_graph.py", line 414, in _save_dot
I just modified
`handle.write(self._current_dotcode)`
by
`handle.write(self._current_dotcode.encode('utf-8'))`

and it's working fine.

**Comment by RoeschFlo** [comment]
Thank you :D

**Comment by ItsJas** [comment]
I recently encountered the same issue, and I found that @alexvaut's encoding fix resolved the problem on the saving side. However, to properly load the saved .dot graph, a decoding fix is also necessary.
```
399c399
<         self._update_graph_view(dotcode)
---
>         self._update_graph_view(dotcode.decode('utf-8')) # fix .dot graph loading
```
I know this is an older issue, but I wanted to add this for completeness!
